### ISSUE TITLE
would you help me ? I have two questions,thank u

### ISSUE THREAD

**Issue by wuxinqiaqiayong** [acojon/packer-redhat#1]
1, is the rhel'ks.cfg file in the iso?
2, after detemining  host ip, the Host IP for hyperv machine is not settling down,so,the ip is incorrect ,and time of connectting vm is always timeout,can you meeting or sovling it

Amount of time to wait for VM's IP to settle down, sometimes VM may report incorrect IP initially, then its recommended to set that parameter to apx. 2 minutes. Examples 45s and 10m. Defaults to 5s(5 seconds). See the Go Lang ParseDuration documentation for full details.

**Comment by acojon** [comment]
Hello.

1) In the /unattended folder is a kickstart.cfg file.  This file is copied to the Debian box and placed in the /root/rhel-install folder.  During the copy the file is renamed to ks.cfg.  When the rhel-ks.iso is created, the ks.cfg is copied into the rhel-ks.iso file.

2) I'm not certain where in the process you are when you experience this error.  Is this during the first stage when you type 'vagrant up' to initialize the build server?
